sBt2
mslehre/text-embedding pull request #31
Opened 2023-05-31 07:25 UTC by LouisaHenze

In website.py the method input_files was changed to compute_similarities_of_files that computes the cosine similarity of two files a user specified in a web form. The cosine similarity is returned in a textfield of the web form.

Problem: If one of the computed embeddings is None, the cosine similarity cannot be computed. Therefore there is a message in the textfield that the file is probably too large to compute an embedding of it. But if the user did not set the openai api key as environment variable, the method to compute the embedding also returns None. At the moment the string in the textfield just says that the file is probably too large which is not necessarily the case if the key is not set, but you get a message in terminal that the key has to be set as environment variable. Should it be added to the displayed text in the textfield that the openai api key may not be set as environment variable?

2023-05-31 14:49 UTC, MarioStanke requested changes
If an input file is too large, the app does not respond gracefully. Please cut it at max_tokens instead. For this you have to remove the `return [None]` from `embedding_from_string`.

A user/developer should know what to input, i.e. they have to place a text file where they executed the website.py server starting script. Please add this to the doc string description of the arguments.

There are further issues with the app that Lukasz has to address.

2023-05-31 14:49 UTC, MarioStanke commented on src/website.py
> +    <label for="fname">Enter first file file: </label><br>
file file -> file name
This makes sense under limited use cases only. Usually the server and client are different computers.
The server must be able to run Python, with the special libraries and OPEN_API_KEY. The client is just some computer with a browser. Only in this limited development setting the server and client are the same computer. 
The file must be on the server in a particular directory.

2023-05-31 14:49 UTC, MarioStanke commented on src/website.py
> +      return "<p>File does not exist</p>"
```suggestion
      return "<p>At least one file does not exist on the server.</p>"
```

2023-06-01 10:21 UTC, LouisaHenze commented
> If an input file is too large, the app does not respond gracefully. Please cut it at max_tokens instead. For this you have to remove the `return [None]` from `embedding_from_string`.
> 
> A user/developer should know what to input, i.e. they have to place a text file where they executed the website.py server starting script. Please add this to the doc string description of the arguments.
> 
> There are further issues with the app that Lukasz has to address.

I cannot only remove `return [None]` from `embedding_from_string`. The problem is that `embedding_from_string` computes the embedding of the string and not of the tokens. Therefore, if the string that should be embedded is too long (because it is encoded in too many tokens) `embedding_from_string` can notice that the string is too long by computing the number of tokens for the string. But you do not get a shorter string that has exactly the maximum number of tokens (the first max number of tokens of tokens of the original string) if it is encoded. Because the string is not changed in `embedding_from_string` the embedding of a string that is too long cannot be computed. 
I would suggest to write a `decode` function in tokenizer.py  and then change  `embedding_from_string` such that it computes with the  `decode` function a shorter string and embedds it.

2023-06-01 18:51 UTC, MarioStanke approved these changes
Ich hatte schon wieder vergessen, dass wir das Embedding direkt nicht von den Tokens bekommen, sondern nur vom String.
Looks good.

2023-06-01 18:51 UTC, merged