Set3
mslehre/text-embedding pull request #36
Opened 2023-06-06 12:37 UTC by MarGabor

Pull request to merge sEt3 into master.
-python code to automatically read IDs from spreadsheet and get names and links of publications from author page in webofscience,com via javascript execution
-manual log in required
-error logging
-data generated added to repo

2023-06-06 14:04 UTC, MarGabor commented
Habe ausversehen auch "lazlostrange" als reviewer angefragt. Kann ignoriert werden.

2023-06-06 14:57 UTC, MarioStanke commented
Why are there only 31 publication lists? Did the others fail?

2023-06-06 19:13 UTC, MarGabor commented
> Why are there only 31 publication lists? Did the others fail?

It must be that the others have either no publications listed on WOS or have no WOS-ID at all.

2023-06-06 19:18 UTC, MarGabor commented
I'll have a look at the dataAcquisitionLog.txt and see if I can find a page, where it timed out although there are publications listed. But I personally suspect that people have not actually created an accoount on WOS.

2023-06-06 19:26 UTC, MarioStanke commented
For example Roland Pulch is missing and has publications:
https://www.webofscience.com/wos/author/record/29340731

2023-06-06 19:28 UTC, MarioStanke commented
We should have 86 publication lists because WoS has only authors (by definition >0 publications).

2023-06-06 19:34 UTC, MarGabor commented
Mhh strange. I supervised the process and regularly there was a page that said that "this page is algorithmically generated". Maybe some kind of covert bot protection?

2023-06-06 19:37 UTC, MarGabor commented
Actually I can't see the page of Roland Pulch, either.

2023-06-09 11:42 UTC, MarGabor commented
Will push new changes. No merging required yet. Managed to get 102 lists extracted this time with use of VPN and institutional login. The problem with that seems to be that I get a random "Access denied" error most of the time when I log in in the headless browser. So this is far from being consistent. But I managed to log in at least once and could extract almost all of the data. (s. dataAcquisitionLog.txt for details, once changes are pushed). I'm trying to push the last two remaining literature lists, too. But my access is denied right now, so I will try again later. Will request new review once I think it's finished.

2023-06-10 10:58 UTC, MarioStanke commented
Good. Please let me explicitly know when I should review (Will push new changes. No merging required yet.)

2023-06-12 09:59 UTC, MarGabor commented
Locally merged. Review can begin.

2023-06-13 06:30 UTC, MarioStanke requested changes
Good job. 
However, please use the IDs from `data/prof.tbl`, e.g. Christiane Helm has ID 8.
Please put a description, how it is run in `src/Readme.md`.

2023-06-13 06:30 UTC, MarioStanke commented on src/dataAcquisition/dataAcquisition.py
> +    spreadsheet = pandas.read_csv("../../data/ProfsGW-proflist.csv")
Should be `prof.tbl`.

2023-06-13 06:30 UTC, MarioStanke commented on src/dataAcquisition/dataAcquisition.py
> +    1. Make sure all sessions for WOS are ended in other browsers.
Copy or move to README.md

2023-06-13 06:30 UTC, MarioStanke commented on src/dataAcquisition/dataAcquisition.py
> +    names_IDs_URLs = df[["Vorname","Nachname","ID"]]
```suggestion
    names_IDs_URLs = df[["firstname","lastname","WoSID","id"]]
```
id is ours, WoSID is from WebOfScience

2023-06-13 06:30 UTC, MarioStanke commented on src/dataAcquisition/dataAcquisition.py
> +    i = 1
not `i` but `sub_df["id"]`

2023-06-13 06:30 UTC, MarioStanke commented on src/dataAcquisition/dataAcquisition.py
> +    main()
newline

2023-06-13 06:30 UTC, MarioStanke commented on src/dataAcquisition/js_scripts/linkgrabber.js
> +//}
newline

2023-06-13 06:30 UTC, MarioStanke commented on src/dataAcquisition/dataAcquisition.py
> +            file.write("["+dtstr+"]\tError: Page \""+URL
For spacing see coding style.

2023-06-13 06:30 UTC, MarioStanke commented on src/dataAcquisition/js_scripts/wos_gotItClicker.js
> +//}
\n

2023-06-13 14:51 UTC, MarioStanke approved these changes
Looks good. There was just one unanswered comment. I will correct the coding style there myself.

2023-06-13 14:51 UTC, MarioStanke commented on src/dataAcquisition/dataAcquisition.py
> +            file.write("["+dtstr+"]\tError: Page \""+URL
Coding style. Spaces around +
```
# Correct:
i = i + 1
submitted += 1
x = x*2 - 1
hypot2 = x*x + y*y
c = (a+b) * (a-b)
# Wrong:
i=i+1
submitted +=1
x = x * 2 - 1
hypot2 = x * x + y * y
c = (a + b) * (a - b)
```

2023-06-13 14:51 UTC, MarioStanke commented on src/dataAcquisition/dataAcquisition.py
>              file.write("["+dtstr+"]\tError: Page \""+URL
```suggestion
            file.write("[" + dtstr + "]\tError: Page \"" + URL
```

2023-06-13 14:51 UTC, merged