Slt2
mslehre/text-embedding pull request #74
Opened 2023-07-02 17:59 UTC by f-bayer15

Created a function to ask the LLM about possible collaboration topics for two researchers. The possible questions can easily be expanded on later.

2023-07-03 05:02 UTC, MarioStanke requested changes
Just inject a few text snippets, see inline comments.

2023-07-03 05:02 UTC, MarioStanke commented on src/justify_similarities.py
> +    answer = get_answer(question, text_dir, text_list)
How are the publication lists separated? I believe only by a newline and relying on the name being in the first line and being recognized as such. That is not clear. Some publication titles could start with a name, too, e.g. "Vorname Name, eine Biografie". Please make it clear, e.g.

<Researcher 1>
...


<Researcher 2>
...

2023-07-05 06:49 UTC, f-bayer15 commented
made the requested changes and added a seperator list argument to explicitely seperate the chunks from each other. Ready to e reviewed again.

2023-07-05 09:36 UTC, MarioStanke approved these changes
LGTM

2023-07-05 10:13 UTC, merged