sJ
mslehre/text-embedding pull request #75
Opened 2023-07-04 12:18 UTC by MarGabor

Corrected some things. I'm especially unsure about the vector representations of the embeddings. If you see any flaws, I'll try to correct them by tomorrow.

2023-07-04 14:36 UTC, MarioStanke commented on docs/README.md
> +# Using OpenAI embeddings for creation of LLM with custom corpus
```suggestion
# Using OpenAI Embeddings in Order to Use an LLM with a Custom Corpus
```

2023-07-04 19:56 UTC, MarGabor commented
So, I implemented the changes, but I'm not sure why the overview.png is not updating in the MD file itself. When I click on it, it redirects me to the image, which is displayed correctly. But scrolling through the MD, it's still somehow cached(?) the old PNG. Maybe it will update after some time?

2023-07-05 06:09 UTC, MarioStanke requested changes
Crop the image.

The pdf display problem is on the side of GitHub Markdowns, and it does not work even if the viewers browser supports pdf. Please link to the PDF in the first place.

2023-07-05 06:09 UTC, MarioStanke commented on docs/overview.png
crop the image

2023-07-05 08:58 UTC, MarGabor commented
Should be alright now. GitHub seems to need quite some time to update the display of the images in MD files. If you like, we can wait for the image to update and I request a new review, once it has.

2023-07-05 10:18 UTC, MarGabor commented
Image is now updated.

2023-07-05 11:10 UTC, MarioStanke approved these changes

2023-07-05 11:10 UTC, merged