sPt1
mslehre/text-embedding pull request #87
Opened 2023-07-17 08:30 UTC by MarGabor

Added a button to the main page that directs to a new page where a grant call text can be entered. Upon clicking "calculate" button, a list of k(here k=10) most similar scientist along with their similarity is displayed.

I cannot connect to http://141.53.34.56, yet. Thus, I decided to leave the page running on localhost for now.

2023-07-17 09:12 UTC, MarioStanke requested changes

2023-07-17 09:12 UTC, MarioStanke commented on src/templates/displayGrantCallResult.html
> +</html>
newline at end of last line, also in another file

2023-07-17 09:12 UTC, MarioStanke commented on src/website.py
> +
This is outdated.  "embeddings" "ids"
![image](https://github.com/mslehre/text-embedding/assets/6883366/faac7511-7136-4554-a4ea-d7a77021fa5f)

2023-07-18 11:52 UTC, MarGabor commented
Fixed stuff. Still runs locally, though.

2023-07-18 12:38 UTC, MarioStanke requested changes
See individual comments.

2023-07-18 12:38 UTC, MarioStanke commented on src/templates/grantCallForm.html
> +        <form action = "http://localhost:5000/grantcallResult" method = "post">
```suggestion
        <form action = "/grantcallResult" method = "post">
```
`localhost` would link to the client computer. The LLM functions must be executed on the host, however.

2023-07-18 12:38 UTC, MarioStanke commented on src/website.py
> +                                   , text1="Please enter a text.")
```suggestion
        return render_template("displayGrantCallResult.html",
                                text1="Please enter a text.")
```
Comma on old line.

2023-07-18 12:38 UTC, MarioStanke commented on src/website.py
> +    #k most similar scientists to display
```suggestion
    # k most similar scientists to display
```
Space after hash sign. See coding style.

2023-07-18 12:38 UTC, MarioStanke commented on src/website.py
> +                                   , text1="Please enter a text.")
Space around binary operator (=). Comma on old line. See coding style.

2023-07-18 12:38 UTC, MarioStanke commented on src/website.py
> +    for i in range(0,k-1):
```suggestion
    for i in range(0, k-1):
```

2023-07-18 12:38 UTC, MarioStanke commented on src/website.py
> +        similarityList.append((similarity, int(ids.iat[j,0])))
```suggestion
        similarityList.append((similarity, int(ids.iat[j, 0])))
```

2023-07-18 12:38 UTC, MarioStanke commented on src/website.py
> +    return render_template("displayGrantCallResult.html", text1=outputText)
```suggestion
    return render_template("displayGrantCallResult.html", text1 = outputText)
```

2023-07-18 12:38 UTC, MarioStanke commented on src/website.py
> +    for i in range(0,k-1):
This is buggy and will fail if *k* is larger than the number of embedded texts. This functionality has been implemented before in `chunks_for_question.get_k_IDs`

2023-07-18 20:33 UTC, MarGabor commented
Implemented suggested changes. I could've probably created a new file for the code and encapsulated it more for the purpose of despaghettification. But alas.

2023-07-19 05:56 UTC, MarioStanke approved these changes
LGTM
I will reset k = 10 and commit myself.

2023-07-19 05:56 UTC, MarioStanke commented on src/website.py
> +    k = 109
```suggestion
    k = 10
```

2023-07-19 05:56 UTC, MarioStanke commented on src/website.py
> +    for i in range(0, k-1):
```suggestion
    for i in range(k):
```

2023-07-19 05:57 UTC, merged